# -*- coding: utf-8 -*-
"""WEEK 4 -  Student Performance Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UST91UuAZ1_v4cNWMm9oqEu0_3njDv_o
"""

!pip install faker

import pandas as pd
import numpy as np
import random
from faker import Faker
import matplotlib.pyplot as plt
import seaborn as sns

fake = Faker()

genders = ["Male", "Female"]
departments = ["CSE", "IT", "ECE"]
years = ["1st", "2nd", "3rd"]

data = []

for i in range(1, 251):
    student = {
        "Student_ID": i,
        "Name": fake.name(),
        "Gender": random.choice(genders),
        "Department": random.choice(departments),
        "Year": random.choice(years),
        "Maths": random.randint(0, 100),
        "Science": random.randint(0, 100),
        "English": random.randint(0, 100),
        "Attendance": random.33(50, 100),
        "Internal_Marks": random.randint(0, 25)
    }
    data.append(student)

df = pd.DataFrame(data)

df.head()

print("Missing Values:\n", df.isnull().sum())

df = df.drop_duplicates()

print("\nDataset Shape:", df.shape)

df["Total"] = df["Maths"] + df["Science"] + df["English"]


df["Average"] = df["Total"] / 3

def grade(avg):
    if avg >= 80:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 40:
        return "C"
    else:
        return "Fail"


df["Grade"] = df["Average"].apply(grade)

print(df.head())

df.describe()

top_students = df.sort_values(by="Average", ascending=False).head(5)
fail_students = df[df["Grade"] == "Fail"]

print("Top 5 Students:\n")
print(top_students)

print("\nFail Students:\n")
print(fail_students)

print("Department-wise Average:\n")
print(df.groupby("Department")["Average"].mean())

print("\nGender-wise Average:\n")
print(df.groupby("Gender")["Average"].mean())

print("\nYear-wise Average:\n")
print(df.groupby("Year")["Average"].mean())

plt.figure(figsize=(6,4))
sns.barplot(x="Department", y="Average", data=df, palette="coolwarm")

plt.title("Department-wise Performance", fontsize=14)
plt.xlabel("Department")
plt.ylabel("Average Marks")

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5,5))

colors = sns.color_palette("pastel")
df["Gender"].value_counts().plot.pie(
    autopct="%1.1f%%",
    colors=colors,
    startangle=90,
    wedgeprops={'edgecolor': 'black'}
)

plt.title("Gender Distribution", fontsize=14)
plt.ylabel("")
plt.show()

plt.figure(figsize=(6,4))

sns.histplot(df["Average"], bins=10, kde=True,color="pink")

plt.title("Average Marks Distribution", fontsize=14)
plt.xlabel("Average Marks")
plt.ylabel("Frequency")

plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

plt.figure(figsize=(6,4))

sns.scatterplot(
    x="Attendance",
    y="Average",
    data=df,
    hue="Department",
    palette="coolwarm"
)

plt.title("Attendance vs Performance", fontsize=14)
plt.xlabel("Attendance (%)")
plt.ylabel("Average Marks")

plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

plt.figure(figsize=(6,4))

sns.scatterplot(
    x="Internal_Marks",
    y="Total",
    data=df,
    hue="Grade",
    palette="coolwarm"
)

plt.title("Internal Marks vs Total Marks", fontsize=14)
plt.xlabel("Internal Marks")
plt.ylabel("Total Marks")

plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()